### ISSUE TITLE
Stops after snapshot

### ISSUE THREAD

**Issue by TeemB** [Omanshu840/Movie-Recommender#19]
Hello I am trying to implement this project but it stops after taking snapshot
Any advice on how to go about this will be really helpful 
Thank you.

**Comment by Saimall** [comment]
check the database details. 
you need to mention your sql database details.
I hope this helps.
thank you..

**Comment by TeemB** [comment]
Unfortunately still not working
by any chance are there any changes i need to make in the dump.sql file
or a specific python version that works best?
